Fix MariaDB Cert Renwal hook script
... so for some reason it doesn't pick up the user config properly (like
running it from the commandline usually does)... but we can explicitly
tell it to use that to fix the issue, so it can actually run the flush
command.

diff --git a/roles/mariadb/templates/mariadb-cert-deploy.sh.j2 b/roles/mariadb/templates/mariadb-cert-deploy.sh.j2
--- a/roles/mariadb/templates/mariadb-cert-deploy.sh.j2
+++ b/roles/mariadb/templates/mariadb-cert-deploy.sh.j2
@@ -17,7 +17,7 @@ if [ -f "$LE_DIR/privkey.pem" ] && [ -f "$LE_DIR/fullchain.pem" ]; then
 
     # Reload MariaDB SSL non-disruptively if running
     if systemctl is-active --quiet mariadb; then
-        mariadb -e "FLUSH SSL;" || echo "Warning: Failed to FLUSH SSL, certificates updated on disk only."
+        mariadb --defaults-extra-file=/root/.my.cnf --socket=/run/mysqld/mysqld.sock -e "FLUSH SSL;" || echo "Warning: Failed to FLUSH SSL, certificates updated on disk only."
     fi
 else
     echo "Certificates not found in $LE_DIR"
